// @generated by protocol/generate_logical_channel_policy.py.
// Source: protocol/logical-channel-policy.yaml. Do not edit.

extension LogicalChannelClass {
    /// Maximum circular service distance while every lane remains ready.
    public var maxServiceGap: Int {
        switch self {
        case .control: return 5
        case .input: return 5
        case .ui: return 8
        case .terminalHigh: return 12
        case .terminalNormal: return 14
        case .resource: return 24
        }
    }
}

extension LogicalChannelScheduler {
    /// Deterministic weighted cycle generated from the protocol policy.
    public static let serviceCycle: [LogicalChannelClass] = [
        .control,
        .input,
        .ui,
        .control,
        .input,
        .terminalHigh,
        .control,
        .input,
        .ui,
        .control,
        .input,
        .terminalNormal,
        .control,
        .input,
        .ui,
        .control,
        .input,
        .terminalHigh,
        .ui,
        .control,
        .input,
        .terminalNormal,
        .terminalHigh,
        .resource,
    ]
}
