use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct RegistrySchema {
    #[allow(dead_code)]
    namespace: u32,
    #[allow(dead_code)]
    namespace_name: String,
    #[allow(dead_code)]
    version: String,
    #[allow(dead_code)]
    description: String,
    node_types: Vec<RegistryItem>,
    properties: Vec<RegistryItem>,
    enums: Vec<RegistryEnum>,
    events: Vec<RegistryItem>,
    operations: Vec<RegistryItem>,
}

#[derive(Debug, Deserialize)]
struct RegistryItem {
    id: u32,
    name: String,
    #[allow(dead_code)]
    tier: Option<String>,
    #[allow(dead_code)]
    category: Option<String>,
    #[allow(dead_code)]
    description: Option<String>,
    #[allow(dead_code)]
    #[serde(default)]
    value_type: Option<String>,
}

#[derive(Debug, Deserialize)]
struct RegistryEnum {
    id: u32,
    name: String,
    #[allow(dead_code)]
    tier: Option<String>,
    #[allow(dead_code)]
    description: Option<String>,
    values: Vec<RegistryEnumValue>,
}

#[derive(Debug, Deserialize)]
struct RegistryEnumValue {
    id: u32,
    name: String,
    #[allow(dead_code)]
    description: Option<String>,
}

fn to_upper_snake_case(name: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = name.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() && i > 0 {
            let prev = chars[i - 1];
            if !prev.is_uppercase() && prev != '_' {
                result.push('_');
            }
        }
        result.push(c.to_ascii_uppercase());
    }
    result
}

fn to_pascal_case(name: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for c in name.chars() {
        if c == '_' || c == '-' || c == ' ' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }
    result
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let registry_path = Path::new(&manifest_dir).join("../../protocol/registry.yaml");

    println!("cargo:rerun-if-changed={}", registry_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let content = fs::read_to_string(&registry_path)
        .unwrap_or_else(|e| panic!("Failed to read registry.yaml at {}: {}", registry_path.display(), e));

    let registry: RegistrySchema = serde_yaml::from_str(&content)
        .unwrap_or_else(|e| panic!("Failed to parse registry.yaml at {}: {}", registry_path.display(), e));

    assert_eq!(registry.node_types.len(), 27, "Expected 27 standard node types, parsed {}", registry.node_types.len());
    assert_eq!(registry.properties.len(), 30, "Expected 30 standard properties, parsed {}", registry.properties.len());
    assert_eq!(registry.enums.len(), 12, "Expected 12 standard enums, parsed {}", registry.enums.len());
    assert_eq!(registry.events.len(), 11, "Expected 11 standard events, parsed {}", registry.events.len());
    assert_eq!(registry.operations.len(), 13, "Expected 13 standard operations, parsed {}", registry.operations.len());

    let mut code = String::new();
    code.push_str("// Auto-generated standard registry lookup tables and constants from protocol/registry.yaml\n");
    code.push_str("// Generated by semantic-tree/build.rs using serde_yaml. Do not edit manually.\n\n");

    // Standard Node Types table
    code.push_str("pub static STANDARD_NODE_TYPES: &[(u32, &str)] = &[\n");
    for item in &registry.node_types {
        code.push_str(&format!("    ({}, {:?}),\n", item.id, item.name));
    }
    code.push_str("];\n\n");

    // Standard Properties table
    code.push_str("pub static STANDARD_PROPERTIES: &[(u32, &str)] = &[\n");
    for item in &registry.properties {
        code.push_str(&format!("    ({}, {:?}),\n", item.id, item.name));
    }
    code.push_str("];\n\n");

    // Standard Events table
    code.push_str("pub static STANDARD_EVENTS: &[(u32, &str)] = &[\n");
    for item in &registry.events {
        code.push_str(&format!("    ({}, {:?}),\n", item.id, item.name));
    }
    code.push_str("];\n\n");

    // Standard Operations table
    code.push_str("pub static STANDARD_OPERATIONS: &[(u32, &str)] = &[\n");
    for item in &registry.operations {
        code.push_str(&format!("    ({}, {:?}),\n", item.id, item.name));
    }
    code.push_str("];\n\n");

    // Standard Enums table
    code.push_str("pub static STANDARD_ENUMS: &[(u32, &str)] = &[\n");
    for item in &registry.enums {
        code.push_str(&format!("    ({}, {:?}),\n", item.id, item.name));
    }
    code.push_str("];\n\n");

    // Generated Constants for TypeRef
    code.push_str("impl TypeRef {\n");
    code.push_str("    // Generated Standard Node Type constants from protocol/registry.yaml (§7.2)\n");
    for item in &registry.node_types {
        let const_name = to_upper_snake_case(&item.name);
        code.push_str(&format!("    pub const {}: Self = Self::standard({});\n", const_name, item.id));
        if item.name == "RichText" {
            code.push_str(&format!("    pub const RICHTEXT: Self = Self::standard({});\n", item.id));
        }
    }
    code.push_str("}\n\n");

    // Generated Constants for PropertyRef
    code.push_str("impl PropertyRef {\n");
    code.push_str("    // Generated Standard Property constants from protocol/registry.yaml (§7.4)\n");
    for item in &registry.properties {
        let const_name = to_upper_snake_case(&item.name);
        code.push_str(&format!("    pub const {}: Self = Self::standard({});\n", const_name, item.id));
    }
    code.push_str("}\n\n");

    // Generated Constants for EnumToken
    code.push_str("impl EnumToken {\n");
    code.push_str("    // Generated Standard Enum value constants from protocol/registry.yaml (§7.5)\n");
    for enum_def in &registry.enums {
        let enum_prefix = to_upper_snake_case(&enum_def.name);
        for val in &enum_def.values {
            let val_suffix = to_upper_snake_case(&val.name);
            code.push_str(&format!(
                "    pub const {}_{}: Self = Self::new({}, {});\n",
                enum_prefix, val_suffix, enum_def.id, val.id
            ));
        }
    }
    code.push_str("}\n\n");

    // Generated Typed Standard Enums
    for enum_def in &registry.enums {
        let enum_type_name = format!("Standard{}", enum_def.name);
        code.push_str(&format!("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n"));
        code.push_str(&format!("#[repr(u32)]\n"));
        code.push_str(&format!("pub enum {} {{\n", enum_type_name));
        for val in &enum_def.values {
            let variant_name = to_pascal_case(&val.name);
            code.push_str(&format!("    {} = {},\n", variant_name, val.id));
        }
        code.push_str("}\n\n");

        code.push_str(&format!("impl From<{}> for EnumToken {{\n", enum_type_name));
        code.push_str(&format!("    fn from(val: {}) -> Self {{\n", enum_type_name));
        code.push_str(&format!("        Self::new({}, val as u32)\n", enum_def.id));
        code.push_str("    }\n");
        code.push_str("}\n\n");

        code.push_str(&format!("impl TryFrom<EnumToken> for {} {{\n", enum_type_name));
        code.push_str("    type Error = ();\n");
        code.push_str("    fn try_from(token: EnumToken) -> Result<Self, ()> {\n");
        code.push_str(&format!("        if token.enum_id != {} {{\n", enum_def.id));
        code.push_str("            return Err(());\n");
        code.push_str("        }\n");
        code.push_str("        match token.value_id {\n");
        for val in &enum_def.values {
            let variant_name = to_pascal_case(&val.name);
            code.push_str(&format!("            {} => Ok(Self::{}),\n", val.id, variant_name));
        }
        code.push_str("            _ => Err(()),\n");
        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");
    }

    // Lookup functions for Node Types
    code.push_str("pub fn lookup_standard_node_type(name: &str) -> Option<u32> {\n");
    code.push_str("    match name {\n");
    for item in &registry.node_types {
        code.push_str(&format!("        {:?} => Some({}),\n", item.name, item.id));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("pub fn standard_node_type_name(id: u32) -> Option<&'static str> {\n");
    code.push_str("    match id {\n");
    for item in &registry.node_types {
        code.push_str(&format!("        {} => Some({:?}),\n", item.id, item.name));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Lookup functions for Properties
    code.push_str("pub fn lookup_standard_property(name: &str) -> Option<u32> {\n");
    code.push_str("    match name {\n");
    for item in &registry.properties {
        code.push_str(&format!("        {:?} => Some({}),\n", item.name, item.id));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("pub fn standard_property_name(id: u32) -> Option<&'static str> {\n");
    code.push_str("    match id {\n");
    for item in &registry.properties {
        code.push_str(&format!("        {} => Some({:?}),\n", item.id, item.name));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Lookup functions for Events
    code.push_str("pub fn lookup_standard_event(name: &str) -> Option<u32> {\n");
    code.push_str("    match name {\n");
    for item in &registry.events {
        code.push_str(&format!("        {:?} => Some({}),\n", item.name, item.id));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("pub fn standard_event_name(id: u32) -> Option<&'static str> {\n");
    code.push_str("    match id {\n");
    for item in &registry.events {
        code.push_str(&format!("        {} => Some({:?}),\n", item.id, item.name));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Lookup functions for Operations
    code.push_str("pub fn lookup_standard_operation(name: &str) -> Option<u32> {\n");
    code.push_str("    match name {\n");
    for item in &registry.operations {
        code.push_str(&format!("        {:?} => Some({}),\n", item.name, item.id));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("pub fn standard_operation_name(id: u32) -> Option<&'static str> {\n");
    code.push_str("    match id {\n");
    for item in &registry.operations {
        code.push_str(&format!("        {} => Some({:?}),\n", item.id, item.name));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Lookup functions for Enums
    code.push_str("pub fn lookup_standard_enum(name: &str) -> Option<u32> {\n");
    code.push_str("    match name {\n");
    for item in &registry.enums {
        code.push_str(&format!("        {:?} => Some({}),\n", item.name, item.id));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("pub fn standard_enum_name(id: u32) -> Option<&'static str> {\n");
    code.push_str("    match id {\n");
    for item in &registry.enums {
        code.push_str(&format!("        {} => Some({:?}),\n", item.id, item.name));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("registry_tables.rs");
    fs::write(&dest_path, code).unwrap_or_else(|e| panic!("Failed to write registry_tables.rs: {}", e));
}
