//! PX-008, the R0 release gate: no code path of this application can signal or
//! reconfigure a process (D1 §4 invariants 1 and 18, §7.7, §24; D2 T21).
//!
//! Two independent checks, both repeatable and both run by `cargo test`:
//!
//! * **Sources.** Every production line of `src/` is searched for the ways Rust
//!   code can reach another process: spawning one (`Command`, `Child`,
//!   `tokio::process`), calling the C library or the kernel directly (`unsafe`,
//!   `extern`, `libc`, `nix`, `syscall`), signalling, tracing, re-prioritizing or
//!   re-limiting one by name (`kill(`, `ptrace(`, `setpriority(`, …), writing
//!   any file (`OpenOptions`, `File::create`, `fs::write`, … — there is no other
//!   way to reach `/proc/<pid>/*`, `/sys/fs/cgroup` or `/proc/sys`), the runtime's
//!   PTY facility (the one runtime path that spawns and signals children), and
//!   every way client input reaches application code (`Session::on`,
//!   `on_result`, `on_text_edit`, a model range provider). The manifest must name
//!   only the SRUI runtime and tokio, with no build script.
//!   The only signal API allowed is receiving SIGINT, SIGTERM and the
//!   `--smoke-fixture` SIGUSR1 trigger.
//! * **Binary.** The dynamic symbols the built `srtop` imports are listed with
//!   `nm`. No process-creation, process-reconfiguration or targeted-signal
//!   function may be among them. `kill`, `waitpid` and `waitid` are imported, and
//!   attributed: they are the runtime PTY manager's teardown of PTY children it
//!   spawned itself, and its spawn path is absent from the binary (no `fork`,
//!   `exec*`, `posix_spawn*` or `clone` is imported) and never called by `src/`.
//!
//! What neither can prove: the behaviour of dependencies beyond their imported
//! symbols; a raw `syscall(2)` made by a dependency (Linux imports `syscall` for
//! std's futex, `statx` and pidfd use — `src/` cannot make one without the
//! `unsafe` the source check forbids); code generated by a dependency's macro;
//! or what another program may do to the same processes.
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// Identifiers that must not appear in production code at all (whole words).
const FORBIDDEN_WORDS: &[(&str, &str)] = &[
    ("Command", "spawns or configures a child process"),
    ("CommandExt", "spawns or replaces a process"),
    ("Child", "controls a spawned process"),
    ("unsafe", "FFI or raw system calls"),
    ("extern", "FFI"),
    ("libc", "direct C library calls"),
    ("nix", "direct system calls"),
    ("syscall", "raw system calls"),
    ("OpenOptions", "opens a file for writing"),
    ("OpenOptionsExt", "opens a file for writing"),
    (
        "PTYManager",
        "the runtime facility that spawns and signals PTY children",
    ),
    ("TerminalSpec", "spawns a PTY child"),
    ("create_terminal_node", "spawns a PTY child"),
    ("attach_terminals", "PTY children"),
    ("srui_pty", "PTY children"),
    ("sysinfo", "a collector with process-signalling APIs"),
];

/// Function names that must not be called (a whole word followed by `(`).
const FORBIDDEN_CALLS: &[(&str, &str)] = &[
    ("kill", "signals a process"),
    ("killpg", "signals a process group"),
    ("tgkill", "signals a thread"),
    ("tkill", "signals a thread"),
    ("pidfd_send_signal", "signals a process"),
    ("pidfd_open", "takes a process handle"),
    ("sigqueue", "signals a process"),
    ("raise", "signals"),
    ("ptrace", "traces a process"),
    ("process_vm_writev", "writes another process's memory"),
    ("setpriority", "re-prioritizes a process"),
    ("nice", "re-prioritizes a process"),
    ("sched_setaffinity", "re-pins a process"),
    ("sched_setscheduler", "changes a scheduling policy"),
    ("sched_setparam", "changes a scheduling policy"),
    ("sched_setattr", "changes a scheduling policy"),
    ("setrlimit", "changes resource limits"),
    ("prlimit", "changes another process's limits"),
    ("ioprio_set", "changes I/O priority"),
    ("setpgid", "moves a process between groups"),
    ("setsid", "changes a session"),
    ("fork", "creates a process"),
    ("vfork", "creates a process"),
    ("exec", "replaces a process image"),
    ("execv", "replaces a process image"),
    ("execve", "replaces a process image"),
    ("execvp", "replaces a process image"),
    ("posix_spawn", "creates a process"),
];

/// Paths and call shapes that must not appear (plain substrings).
const FORBIDDEN_TEXT: &[(&str, &str)] = &[
    ("tokio::process", "spawns a process"),
    ("std::os::unix::process", "replaces or configures a process"),
    ("tokio::fs", "asynchronous file writes"),
    ("File::create", "writes a file"),
    ("fs::write", "writes a file"),
    ("fs::remove_file", "deletes a file"),
    ("fs::remove_dir", "deletes a directory"),
    ("fs::remove_dir_all", "deletes a directory tree"),
    ("fs::create_dir", "creates a directory"),
    ("fs::create_dir_all", "creates directories"),
    ("fs::set_permissions", "changes permissions"),
    ("fs::rename", "moves a file"),
    ("fs::copy", "writes a file"),
    ("fs::hard_link", "creates a link"),
    ("fs::symlink", "creates a link"),
    ("#[link", "links a native library"),
    // Client input reaches application code only through a handler the application installs: an
    // event, a text edit or a collection range request. srtop installs none.
    (".on(", "installs a client event handler"),
    (".on_result(", "installs a client event handler"),
    (
        ".on_result_with_transaction(",
        "installs a client event handler",
    ),
    (".on_text_edit(", "installs a client text-edit policy"),
    ("ModelRangeProvider", "answers client range requests"),
    ("run_model_range_worker", "answers client range requests"),
];

/// The signals `main` may *receive*. Sending a signal needs `kill(` or `libc`.
const RECEIVED_SIGNALS: &[&str] = &[
    "SignalKind::interrupt()",
    "SignalKind::terminate()",
    "SignalKind::user_defined1()",
];

/// The only direct dependencies: the SRUI runtime and its async runtime.
const ALLOWED_DEPENDENCIES: &[&str] = &[
    "tokio",
    "tokio-util",
    "srui-protocol",
    "srui-sdk",
    "srui-semantic-tree",
    "srui-sessiond",
    "srui-unix-security",
];

fn is_identifier(character: char) -> bool {
    character.is_alphanumeric() || character == '_'
}

/// Byte offsets where `pattern` occurs in `line` without running into a longer
/// identifier: `fs::symlink` is not `fs::symlink_metadata`, `nix` is not `Unix`.
/// A side of the pattern that is punctuation needs no boundary.
fn word_positions(line: &str, pattern: &str) -> Vec<usize> {
    let open_start = pattern.starts_with(is_identifier);
    let open_end = pattern.ends_with(is_identifier);
    line.match_indices(pattern)
        .filter(|(start, _)| {
            let before = line[..*start].chars().next_back();
            let after = line[start + pattern.len()..].chars().next();
            !(open_start && before.is_some_and(is_identifier))
                && !(open_end && after.is_some_and(is_identifier))
        })
        .map(|(start, _)| start)
        .collect()
}

/// A line with its `//` comment removed. String literals containing `//` lose
/// their tail too, which can only hide text, never invent a match.
fn code(line: &str) -> &str {
    line.find("//").map_or(line, |comment| &line[..comment])
}

/// The production part of a source file: everything before its first
/// column-zero `#[cfg(test)]`. rustfmt (enforced by `cargo fmt --check`) puts
/// every item of a module body below column zero, so a column-zero line after
/// that point is either a test module's own attribute, header or closing brace,
/// or production code placed after the tests — which is reported, not trusted.
fn production_lines(path: &str, text: &str) -> Result<Vec<(usize, String)>, String> {
    let lines: Vec<&str> = text.lines().collect();
    let Some(cut) = lines.iter().position(|line| *line == "#[cfg(test)]") else {
        return Ok(lines
            .iter()
            .enumerate()
            .map(|(index, line)| (index + 1, line.to_string()))
            .collect());
    };
    let mut cfg_test = false;
    for (index, line) in lines.iter().enumerate().skip(cut) {
        let top_level = !line.is_empty() && !line.starts_with([' ', '\t']);
        if !top_level || line.starts_with("//") || *line == "}" {
            continue;
        }
        if *line == "#[cfg(test)]" {
            cfg_test = true;
        } else if line.starts_with("#[") {
            // Further attributes of the same item keep the `cfg(test)` in force.
        } else if line.starts_with("mod ") && line.ends_with('{') && cfg_test {
            cfg_test = false;
        } else {
            return Err(format!(
                "{path}:{}: column-zero code after the test region is not \
                 `#[cfg(test)]`-gated: {line}",
                index + 1
            ));
        }
    }
    Ok(lines[..cut]
        .iter()
        .enumerate()
        .map(|(index, line)| (index + 1, line.to_string()))
        .collect())
}

/// Every forbidden construct in the production part of `text`.
fn violations(path: &str, text: &str) -> Vec<String> {
    let lines = match production_lines(path, text) {
        Ok(lines) => lines,
        Err(error) => return vec![error],
    };
    let mut found = Vec::new();
    for (number, line) in &lines {
        let line = code(line);
        let mut report = |what: &str, why: &str| {
            found.push(format!(
                "{path}:{number}: `{what}` ({why}): {}",
                line.trim()
            ));
        };
        for (word, why) in FORBIDDEN_WORDS {
            if !word_positions(line, word).is_empty() {
                report(word, why);
            }
        }
        for (name, why) in FORBIDDEN_CALLS {
            let called = word_positions(line, name)
                .into_iter()
                .any(|start| line[start + name.len()..].trim_start().starts_with('('));
            if called {
                report(name, why);
            }
        }
        for (text, why) in FORBIDDEN_TEXT {
            if !word_positions(line, text).is_empty() {
                report(text, why);
            }
        }
        for (start, _) in line.match_indices("SignalKind::") {
            if !RECEIVED_SIGNALS
                .iter()
                .any(|allowed| line[start..].starts_with(allowed))
            {
                report(
                    "SignalKind",
                    "a signal other than SIGINT, SIGTERM or SIGUSR1",
                );
            }
        }
    }
    found
}

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn rust_files(directory: &Path, into: &mut Vec<PathBuf>) {
    let mut entries: Vec<PathBuf> = std::fs::read_dir(directory)
        .expect("the source directory is readable")
        .map(|entry| entry.expect("a readable entry").path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            rust_files(&path, into);
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            into.push(path);
        }
    }
}

/// The audit itself is not vacuous: each kind of construct it exists to catch is
/// caught, test code is not production code, and code hidden after a test
/// module is refused rather than skipped.
#[test]
fn the_source_audit_catches_what_it_is_for() {
    for (snippet, expected) in [
        ("let child = std::process::Command::new(\"x\");", "Command"),
        ("tokio::process::Command::new(\"x\");", "tokio::process"),
        ("let _ = worker.kill();", "kill"),
        ("unsafe { libc::kill(pid, 15) };", "unsafe"),
        ("let _ = nix::sys::signal::kill(pid, None);", "nix"),
        (
            "fs::write(\"/proc/1/oom_score_adj\", \"1000\")?;",
            "fs::write",
        ),
        (
            "std::fs::OpenOptions::new().write(true).open(\"/sys/fs/cgroup/x/cgroup.procs\")?;",
            "OpenOptions",
        ),
        (
            "session.create_terminal_node(id, spec)?;",
            "create_terminal_node",
        ),
        ("session.on(TABLE, ACTIVATE, |_| {});", ".on("),
        (
            "session.on_result(TABLE, ACTIVATE, |_, _| Ok(()));",
            ".on_result(",
        ),
        ("let mut hup = signal(SignalKind::hangup())?;", "SignalKind"),
        ("setpriority(0, pid, 19);", "setpriority"),
        ("sched_setaffinity (pid, size, set);", "sched_setaffinity"),
    ] {
        let found = violations("snippet.rs", snippet);
        assert!(
            found
                .iter()
                .any(|violation| violation.contains(&format!("`{expected}`"))),
            "{snippet:?} was not reported as {expected:?}: {found:?}"
        );
    }
    for innocent in [
        "// a comment may say kill(2) and Command",
        "let [user, nice, system] = counts;",
        "let _ = write!(text, \"{byte:02x}\");",
        "let id = std::process::id();",
        "let mut term = signal(SignalKind::terminate())?;",
        "connections.spawn(poll(view, source, session, interval, token));",
        "let token = shutdown.child_token();",
        "let kind = std::fs::symlink_metadata(&path)?;",
    ] {
        assert_eq!(violations("snippet.rs", innocent), Vec::<String>::new());
    }
    let tested =
        "pub fn live() {}\n#[cfg(test)]\nmod tests {\n    fn t() { Command::new(\"x\"); }\n}\n";
    assert_eq!(violations("tested.rs", tested), Vec::<String>::new());
    let hidden = "pub fn live() {}\n#[cfg(test)]\nmod tests {\n}\n\npub fn late() {}\n";
    assert!(violations("hidden.rs", hidden)[0].contains("not `#[cfg(test)]`-gated"));
    let ungated = "#[cfg(test)]\nmod tests {\n}\nmod more {\n}\n";
    assert!(violations("ungated.rs", ungated)[0].contains("mod more"));
}

#[test]
fn no_production_source_can_signal_or_reconfigure_a_process() {
    let root = crate_root();
    let mut files = Vec::new();
    rust_files(&root.join("src"), &mut files);
    assert!(
        files.iter().any(|path| path.ends_with("src/main.rs")),
        "the audit must cover the binary's entry point"
    );
    let mut found = Vec::new();
    let mut audited = Vec::new();
    let mut receivers = 0;
    for path in &files {
        let text = std::fs::read_to_string(path).expect("a readable source file");
        let name = path
            .strip_prefix(&root)
            .unwrap_or(path)
            .display()
            .to_string();
        let production = production_lines(&name, &text).unwrap_or_else(|error| panic!("{error}"));
        receivers += production
            .iter()
            .map(|(_, line)| code(line).matches("SignalKind::").count())
            .sum::<usize>();
        audited.push(format!("{name}:{}", production.len()));
        found.extend(violations(&name, &text));
    }
    assert!(
        found.is_empty(),
        "process control in production code:\n{}",
        found.join("\n")
    );
    // The exceptions, stated: `main` receives SIGINT and SIGTERM to remove its
    // own socket, and SIGUSR1 only under `--smoke-fixture`, to retitle the shell.
    assert_eq!(receivers, RECEIVED_SIGNALS.len());

    // The manifest: only the runtime, no native library, no build script.
    let manifest =
        std::fs::read_to_string(root.join("Cargo.toml")).expect("the manifest is readable");
    let mut section = String::new();
    let mut dependencies = BTreeSet::new();
    for line in manifest.lines().map(str::trim) {
        if line.starts_with('[') {
            section = line.to_string();
            assert!(
                !section.contains("build-dependencies") && !section.starts_with("[target"),
                "unexpected manifest section {section}"
            );
            continue;
        }
        assert!(
            !line.starts_with("build") && !line.starts_with("links"),
            "the package may not run a build script or link a native library: {line}"
        );
        if section == "[dependencies]" {
            if let Some((name, _)) = line.split_once('=') {
                dependencies.insert(name.trim().to_string());
            }
        }
    }
    let allowed: BTreeSet<String> = ALLOWED_DEPENDENCIES
        .iter()
        .map(|name| name.to_string())
        .collect();
    assert_eq!(dependencies, allowed, "direct dependencies changed");
    assert!(!root.join("build.rs").exists(), "no build script");
    println!(
        "PX-008 source audit: {} files, production lines per file {audited:?}; \
         0 violations; signal receivers {RECEIVED_SIGNALS:?}; dependencies {dependencies:?}",
        files.len()
    );
}

/// Imports that would let the binary create, signal, trace or reconfigure a
/// process. None may be present.
const FORBIDDEN_IMPORTS: &[&str] = &[
    // creating a process or replacing its image
    "fork",
    "vfork",
    "clone",
    "clone3",
    "execve",
    "execv",
    "execvp",
    "execvpe",
    "execl",
    "execlp",
    "execle",
    "fexecve",
    "posix_spawn",
    "posix_spawnp",
    "system",
    "popen",
    // targeted signals beyond the attributed `kill`
    "killpg",
    "tgkill",
    "tkill",
    "pidfd_send_signal",
    "pidfd_open",
    "sigqueue",
    "pthread_kill",
    "raise",
    // tracing or another process's memory
    "ptrace",
    "process_vm_writev",
    "process_vm_readv",
    "task_for_pid",
    // reconfiguring a process
    "setpriority",
    "nice",
    "sched_setaffinity",
    "sched_setscheduler",
    "sched_setparam",
    "sched_setattr",
    "setrlimit",
    "setrlimit64",
    "prlimit",
    "prlimit64",
    "ioprio_set",
    "setpgid",
    "setsid",
    "setpgrp",
    "thread_policy_set",
    "task_policy_set",
    "setiopolicy_np",
    "proc_rlimit_control",
];

/// Imports present for a stated reason that is not this application's.
const ATTRIBUTED_IMPORTS: &[(&str, &str)] = &[
    (
        "kill",
        "srui-pty TerminalStream teardown (signal_child_tree, Child::kill) of a PTY child \
         only PTYManager::spawn creates; spawn is absent (no process-creation import) and \
         never called by src/",
    ),
    ("waitpid", "the same teardown reaping the same PTY child"),
    (
        "waitid",
        "the same teardown reaping the same PTY child (Linux std)",
    ),
    (
        "syscall",
        "std/tokio raw system calls (futex, statx, getrandom, pidfd); src/ cannot make \
         one without unsafe",
    ),
];

#[test]
fn the_binary_imports_no_process_creation_signalling_or_reconfiguration_function() {
    let binary = env!("CARGO_BIN_EXE_srtop");
    let arguments: &[&str] = if cfg!(target_os = "macos") {
        &["-u"]
    } else {
        &["-D", "--undefined-only"]
    };
    let output = Command::new("nm")
        .args(arguments)
        .arg(binary)
        .stdin(Stdio::null())
        .stderr(Stdio::piped())
        .output()
        .expect("nm is required for the import audit; it is never skipped");
    assert!(
        output.status.success(),
        "nm failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let imports: BTreeSet<String> = String::from_utf8_lossy(&output.stdout)
        .lines()
        .filter_map(|line| line.split_whitespace().last())
        .map(|symbol| {
            let symbol = symbol.split('@').next().unwrap_or(symbol);
            let symbol = if cfg!(target_os = "macos") {
                symbol.strip_prefix('_').unwrap_or(symbol)
            } else {
                symbol
            };
            symbol.to_string()
        })
        .collect();
    assert!(
        imports.contains("read") && imports.len() > 20,
        "implausible import list from nm: {imports:?}"
    );
    let forbidden: Vec<&str> = FORBIDDEN_IMPORTS
        .iter()
        .copied()
        .filter(|symbol| imports.contains(*symbol))
        .collect();
    assert!(
        forbidden.is_empty(),
        "srtop imports process-control functions: {forbidden:?}"
    );
    let attributed: Vec<String> = ATTRIBUTED_IMPORTS
        .iter()
        .filter(|(symbol, _)| imports.contains(*symbol))
        .map(|(symbol, reason)| format!("{symbol}: {reason}"))
        .collect();
    println!(
        "PX-008 import audit ({}): {} imported symbols; forbidden present: none; \
         attributed: {attributed:?}; all: {imports:?}",
        std::env::consts::OS,
        imports.len()
    );
}
