#!/usr/bin/env python3
"""
SRUI Conformance Matrix Generator (§32 suites 2, 5 and 12).

Generates the shared, language-neutral fixtures consumed by the widget-semantics,
semantic-input and toolkit-mapping conformance suites:

    protocol/conformance-vectors/suites/02-widget-semantics/widgets.generated.json
    protocol/conformance-vectors/suites/05-semantic-input/events.generated.json
    protocol/conformance-vectors/suites/12-toolkit-mapping/mappings.generated.json

Everything the registry owns — node id, name, tier, category, and the `emits` matrix
(§7.6) — is read from protocol/registry.yaml rather than restated here, so a widget
promoted from `should` to `required` cannot leave a stale copy behind in a fixture.

The one table that is *not* registry-derived is the AppKit mapping. §22.4 makes native
mappings explicitly informative: a renderer may change them without a protocol version
change, so they must not become protocol source of truth. It lives here, keyed by node
name, and `_appkit_mapping_for` fails loudly when the registry gains a node type the
table does not cover — the same fail-closed contract the registry count asserts in
server-rust/semantic-tree/build.rs provide.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

PROTOCOL_DIR = Path(__file__).resolve().parent
if str(PROTOCOL_DIR) not in sys.path:
    sys.path.insert(0, str(PROTOCOL_DIR))

from validate.loader import load_registry  # noqa: E402

GENERATED_BANNER = (
    "GENERATED by protocol/generate_conformance_matrix.py from protocol/registry.yaml. "
    "Do not edit by hand; run ./protocol/generate_proto.sh and commit the result."
)

# Informative AppKit realisation per §22.4 and §32.12. `view` records the class the
# macOS renderer actually constructs in client-macos/RendererAppKit/ControlFactory.swift;
# `planned` entries are node types ControlFactory currently rejects with
# `ControlFactoryError.unsupportedNodeType`.
APPKIT_MAPPINGS: dict[str, dict[str, str]] = {
    "Surface": {"view": "NSWindow + NSStackView", "strategy": "window with vertical content stack"},
    "Dialog": {"view": "NSPanel", "strategy": "transient panel over the parent surface"},
    "Row": {"view": "NSStackView", "strategy": "horizontal orientation"},
    "Column": {"view": "NSStackView", "strategy": "vertical orientation"},
    "Grid": {"view": "NSGridView", "strategy": "two-dimensional row/column placement"},
    "Spacer": {"view": "NSView", "strategy": "empty flexible view driving stack distribution"},
    "Separator": {"view": "NSBox", "strategy": "separator box style"},
    "Scroll": {"view": "NSScrollView", "strategy": "scroll view over a document stack"},
    "Text": {"view": "NSTextField", "strategy": "non-editable label field"},
    "RichText": {"view": "NSTextView", "strategy": "selectable non-editable text view"},
    "Button": {"view": "NSButton", "strategy": "push button with target/action trampoline"},
    "Toggle": {"view": "NSButton", "strategy": "checkbox button type"},
    "TextInput": {"view": "NSTextField", "strategy": "editable single-line field with local edit adapter"},
    "TextArea": {"view": "NSScrollView + NSTextView", "strategy": "scrollable editable text view"},
    "Progress": {"view": "NSProgressIndicator", "strategy": "determinate or indeterminate bar"},
    "Image": {"view": "NSImageView", "strategy": "image view fed by the resource cache"},
    "List": {"view": "NSTableView", "strategy": "single-column virtualized table"},
    "Table": {"view": "NSTableView", "strategy": "multi-column virtualized table"},
    "Tree": {"view": "NSOutlineView", "strategy": "outline view with disclosure triangles"},
    "Select": {"view": "NSPopUpButton", "strategy": "pull-down/pop-up single selection"},
    "ChoiceGroup": {"view": "NSSegmentedControl", "strategy": "segmented control or radio group"},
    "Slider": {"view": "NSSlider", "strategy": "continuous or stepped slider"},
    "NumberInput": {"view": "NSTextField + NSStepper", "strategy": "numeric field with stepper"},
    "Tabs": {"view": "NSTabView", "strategy": "tab view with one item per page child"},
    "Split": {"view": "NSSplitView", "strategy": "user-resizable split panes"},
    "Menu": {"view": "NSMenu", "strategy": "menu hierarchy attached to the main menu bar"},
    "Toolbar": {"view": "NSToolbar", "strategy": "window toolbar with identified items"},
}

# §7.3 tiers whose node types the macOS renderer is expected to construct today. Anything
# outside this set must fail closed rather than render a degraded approximation (§4 inv. 13).
IMPLEMENTED_TIERS = frozenset({"required"})


def _appkit_mapping_for(node_name: str) -> dict[str, str]:
    mapping = APPKIT_MAPPINGS.get(node_name)
    if mapping is None:
        raise KeyError(
            f"registry.yaml declares node type '{node_name}' with no AppKit mapping in "
            "APPKIT_MAPPINGS (protocol/generate_conformance_matrix.py). Add one — an "
            "informative mapping is still required for §32 suite 12 to stay complete."
        )
    return mapping


def _node_rows(registry: dict) -> list[dict]:
    """Registry-derived per-node facts shared by all three generated fixtures."""
    rows = []
    for entry in registry.get("node_types", []):
        name = entry["name"]
        tier = entry.get("tier")
        rows.append(
            {
                "id": entry["id"],
                "name": name,
                "tier": tier,
                "category": entry.get("category"),
                "emits": list(entry.get("emits", [])),
                "renderer_implemented": tier in IMPLEMENTED_TIERS,
            }
        )
    rows.sort(key=lambda row: row["id"])
    return rows


def build_widget_matrix(registry: dict) -> dict:
    """§32.2 — event/state meaning for each Standard Widget node type."""
    return {
        "$generated": GENERATED_BANNER,
        "suite": 2,
        "suite_name": "widget-semantics",
        "spec_sections": ["§7.2", "§7.3", "§7.6", "§32.2"],
        "node_types": [
            {
                "id": row["id"],
                "name": row["name"],
                "tier": row["tier"],
                "category": row["category"],
                "emits": row["emits"],
                # A node type outside the required tier must be rejected outright by the
                # renderer rather than silently substituted (§4 inv. 13, §7.3).
                "expect_constructible": row["renderer_implemented"],
            }
            for row in _node_rows(registry)
        ],
    }


def build_event_matrix(registry: dict) -> dict:
    """§32.5 — semantic actions for standard controls; coordinates only for subscribed scenes."""
    events = registry.get("events", [])
    semantic = sorted(ev["name"] for ev in events if ev.get("kind") == "semantic")
    coordinate = sorted(ev["name"] for ev in events if ev.get("kind") == "coordinate")

    return {
        "$generated": GENERATED_BANNER,
        "suite": 5,
        "suite_name": "semantic-input",
        "spec_sections": ["§7.6", "§7.7", "§32.5"],
        "semantic_events": semantic,
        # §7.7: reserved for explicitly subscribed custom scene nodes. No Standard Widget
        # Profile node type may originate one, which is the core assertion of this suite.
        "coordinate_events": coordinate,
        "node_event_matrix": [
            {
                "node": row["name"],
                "tier": row["tier"],
                "allowed": row["emits"],
                "forbidden": coordinate,
            }
            for row in _node_rows(registry)
        ],
    }


def build_toolkit_mappings(registry: dict) -> dict:
    """§32.12 — informative cross-renderer mapping fixture (§22.4: not normative)."""
    return {
        "$generated": GENERATED_BANNER,
        "suite": 12,
        "suite_name": "toolkit-mapping",
        "spec_sections": ["§22.4", "§32.12"],
        # §22.4: a renderer may change these without a protocol version change. Conformance
        # asserts the mapping table is complete and honest about what is implemented, never
        # that a particular NSView class was used.
        "normative": False,
        "mappings": [
            {
                "node": row["name"],
                "tier": row["tier"],
                "category": row["category"],
                "appkit_view": _appkit_mapping_for(row["name"])["view"],
                "appkit_strategy": _appkit_mapping_for(row["name"])["strategy"],
                "implemented": row["renderer_implemented"],
            }
            for row in _node_rows(registry)
        ],
    }


def _write_json_atomically(payload: dict, output_path: Path) -> None:
    contents = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_mode = output_path.stat().st_mode & 0o777 if output_path.exists() else 0o644
    file_descriptor, temporary_name = tempfile.mkstemp(
        dir=output_path.parent,
        prefix=f".{output_path.name}.",
        suffix=".tmp",
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(file_descriptor, output_mode)
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as output_file:
            output_file.write(contents)
            output_file.flush()
            os.fsync(output_file.fileno())
        os.replace(temporary_path, output_path)
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise


def generate_conformance_matrix(registry_path: Path, suites_dir: Path) -> dict[Path, dict]:
    """Generate all three fixtures. Returns the written path -> payload mapping."""
    registry = load_registry(registry_path)

    outputs = {
        suites_dir / "02-widget-semantics" / "widgets.generated.json": build_widget_matrix(registry),
        suites_dir / "05-semantic-input" / "events.generated.json": build_event_matrix(registry),
        suites_dir / "12-toolkit-mapping" / "mappings.generated.json": build_toolkit_mappings(registry),
    }
    for output_path, payload in outputs.items():
        _write_json_atomically(payload, output_path)
        print(f"Generated conformance matrix -> {output_path}")
    return outputs


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    registry_file = repo_root / "protocol" / "registry.yaml"
    suites_dir = repo_root / "protocol" / "conformance-vectors" / "suites"

    if not registry_file.exists():
        raise FileNotFoundError(f"Registry file not found at {registry_file}")

    generate_conformance_matrix(registry_file, suites_dir)


if __name__ == "__main__":
    main()
