#!/usr/bin/env python3
"""Generate the Rust and Swift logical-channel scheduling policy."""

from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
POLICY_PATH = REPO_ROOT / "protocol" / "logical-channel-policy.yaml"
RUST_OUTPUT = (
    REPO_ROOT
    / "server-rust"
    / "sessiond"
    / "src"
    / "outbound"
    / "logical_channel_policy.generated.rs"
)
SWIFT_OUTPUT = (
    REPO_ROOT
    / "client-macos"
    / "TransportSSH"
    / "LogicalChannelPolicy.generated.swift"
)
_CLASS_NAME = re.compile(r"^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$")
_EXPECTED_CYCLE_LENGTH = 24


@dataclass(frozen=True)
class LogicalChannelPolicy:
    """Validated scheduling policy and its derived circular service gaps."""

    classes: tuple[str, ...]
    service_cycle: tuple[str, ...]
    max_service_gaps: dict[str, int]


def _require_string_list(raw: object, field: str) -> tuple[str, ...]:
    if not isinstance(raw, list) or not raw:
        raise ValueError(f"{field} must be a non-empty list")
    if not all(isinstance(value, str) for value in raw):
        raise ValueError(f"{field} entries must all be strings")
    return tuple(raw)


def load_policy(path: Path) -> LogicalChannelPolicy:
    """Load and validate the canonical policy, deriving circular gap bounds."""

    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise TypeError("logical-channel policy must be a mapping")
    unknown_fields = set(raw) - {"version", "classes", "service_cycle"}
    if unknown_fields:
        raise ValueError(f"unknown policy fields: {sorted(unknown_fields)}")
    if raw.get("version") != 1:
        raise ValueError("logical-channel policy version must be 1")

    classes = _require_string_list(raw.get("classes"), "classes")
    if len(classes) != len(set(classes)):
        raise ValueError("classes must not contain duplicates")
    invalid_names = [name for name in classes if _CLASS_NAME.fullmatch(name) is None]
    if invalid_names:
        raise ValueError(f"invalid class names: {invalid_names}")

    service_cycle = _require_string_list(raw.get("service_cycle"), "service_cycle")
    if len(service_cycle) != _EXPECTED_CYCLE_LENGTH:
        raise ValueError(
            f"service_cycle must contain exactly {_EXPECTED_CYCLE_LENGTH} slots"
        )
    unknown_classes = sorted(set(service_cycle) - set(classes))
    missing_classes = sorted(set(classes) - set(service_cycle))
    if unknown_classes:
        raise ValueError(f"service_cycle contains unknown classes: {unknown_classes}")
    if missing_classes:
        raise ValueError(f"service_cycle omits classes: {missing_classes}")

    max_service_gaps: dict[str, int] = {}
    cycle_length = len(service_cycle)
    for name in classes:
        positions = [
            index for index, candidate in enumerate(service_cycle) if candidate == name
        ]
        circular_positions = positions[1:] + [positions[0] + cycle_length]
        max_service_gaps[name] = max(
            later - earlier
            for earlier, later in zip(positions, circular_positions, strict=True)
        )

    return LogicalChannelPolicy(classes, service_cycle, max_service_gaps)


def _pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _camel_case(name: str) -> str:
    head, *tail = name.split("_")
    return head + "".join(part.capitalize() for part in tail)


def render_rust(policy: LogicalChannelPolicy) -> str:
    """Render the Rust policy constants and derived gap implementation."""

    lines = [
        "// @generated by protocol/generate_logical_channel_policy.py.",
        "// Source: protocol/logical-channel-policy.yaml. Do not edit.",
        "",
        "impl LogicalChannelClass {",
        "    /// Maximum circular service distance while every lane remains ready.",
        "    #[must_use]",
        "    pub const fn max_service_gap(self) -> usize {",
        "        match self {",
    ]
    lines.extend(
        f"            Self::{_pascal_case(name)} => {policy.max_service_gaps[name]},"
        for name in policy.classes
    )
    lines.extend(
        [
            "        }",
            "    }",
            "}",
            "",
            "/// Deterministic weighted cycle generated from the protocol policy.",
            (
                "pub const SERVICE_CYCLE: "
                f"[LogicalChannelClass; {len(policy.service_cycle)}] = ["
            ),
        ]
    )
    lines.extend(
        f"    LogicalChannelClass::{_pascal_case(name)}," for name in policy.service_cycle
    )
    lines.extend(["];", ""])
    return "\n".join(lines)


def render_swift(policy: LogicalChannelPolicy) -> str:
    """Render the Swift policy constants and derived gap implementation."""

    lines = [
        "// @generated by protocol/generate_logical_channel_policy.py.",
        "// Source: protocol/logical-channel-policy.yaml. Do not edit.",
        "",
        "extension LogicalChannelClass {",
        "    /// Maximum circular service distance while every lane remains ready.",
        "    public var maxServiceGap: Int {",
        "        switch self {",
    ]
    lines.extend(
        f"        case .{_camel_case(name)}: return {policy.max_service_gaps[name]}"
        for name in policy.classes
    )
    lines.extend(
        [
            "        }",
            "    }",
            "}",
            "",
            "extension LogicalChannelScheduler {",
            "    /// Deterministic weighted cycle generated from the protocol policy.",
            "    public static let serviceCycle: [LogicalChannelClass] = [",
        ]
    )
    lines.extend(f"        .{_camel_case(name)}," for name in policy.service_cycle)
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def _write_atomic(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    previous_mode = (path.stat().st_mode & 0o777) if path.exists() else None
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as output:
            output.write(contents)
        if previous_mode is not None:
            temporary.chmod(previous_mode)
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def generate_logical_channel_policy(
    policy_path: Path,
    rust_output: Path,
    swift_output: Path,
) -> LogicalChannelPolicy:
    """Validate once, then atomically replace each generated language binding."""

    policy = load_policy(policy_path)
    rust_contents = render_rust(policy)
    swift_contents = render_swift(policy)
    _write_atomic(rust_output, rust_contents)
    _write_atomic(swift_output, swift_contents)
    return policy


def main() -> None:
    generate_logical_channel_policy(POLICY_PATH, RUST_OUTPUT, SWIFT_OUTPUT)
    print(f"Generated Rust logical-channel policy -> {RUST_OUTPUT}")
    print(f"Generated Swift logical-channel policy -> {SWIFT_OUTPUT}")


if __name__ == "__main__":
    main()
