// @generated by protocol/generate_logical_channel_policy.py.
// Source: protocol/logical-channel-policy.yaml. Do not edit.

impl LogicalChannelClass {
    /// Maximum circular service distance while every lane remains ready.
    #[must_use]
    pub const fn max_service_gap(self) -> usize {
        match self {
            Self::Control => 5,
            Self::Input => 5,
            Self::Ui => 8,
            Self::TerminalHigh => 12,
            Self::TerminalNormal => 14,
            Self::Resource => 24,
        }
    }
}

/// Deterministic weighted cycle generated from the protocol policy.
pub const SERVICE_CYCLE: [LogicalChannelClass; 24] = [
    LogicalChannelClass::Control,
    LogicalChannelClass::Input,
    LogicalChannelClass::Ui,
    LogicalChannelClass::Control,
    LogicalChannelClass::Input,
    LogicalChannelClass::TerminalHigh,
    LogicalChannelClass::Control,
    LogicalChannelClass::Input,
    LogicalChannelClass::Ui,
    LogicalChannelClass::Control,
    LogicalChannelClass::Input,
    LogicalChannelClass::TerminalNormal,
    LogicalChannelClass::Control,
    LogicalChannelClass::Input,
    LogicalChannelClass::Ui,
    LogicalChannelClass::Control,
    LogicalChannelClass::Input,
    LogicalChannelClass::TerminalHigh,
    LogicalChannelClass::Ui,
    LogicalChannelClass::Control,
    LogicalChannelClass::Input,
    LogicalChannelClass::TerminalNormal,
    LogicalChannelClass::TerminalHigh,
    LogicalChannelClass::Resource,
];
