[package]
name = "srui-pty"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc = "0.2"
portable-pty = "0.8"
srui-protocol = { path = "../protocol" }
srui-semantic-tree = { path = "../semantic-tree" }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "rt"] }
tracing.workspace = true
