// Auto-generated standard registry lookup tables and constants from protocol/registry.yaml
// Generated by protocol/generate_swift_registry.py. Do not edit manually.

import Foundation

// MARK: - Registry Tables

public let standardNodeTypesTable: [(id: UInt32, name: String, tier: String)] = [
    (1, "Surface", "required"),
    (2, "Dialog", "standard"),
    (3, "Row", "required"),
    (4, "Column", "required"),
    (5, "Grid", "required"),
    (6, "Spacer", "required"),
    (7, "Separator", "required"),
    (8, "Scroll", "required"),
    (9, "Text", "required"),
    (10, "RichText", "required"),
    (11, "Button", "required"),
    (12, "Toggle", "required"),
    (13, "TextInput", "required"),
    (14, "TextArea", "required"),
    (15, "Progress", "required"),
    (16, "Image", "required"),
    (17, "List", "required"),
    (18, "Table", "required"),
    (19, "Tree", "required"),
    (20, "Select", "should"),
    (21, "ChoiceGroup", "should"),
    (22, "Slider", "should"),
    (23, "NumberInput", "should"),
    (24, "Tabs", "should"),
    (25, "Split", "should"),
    (26, "Menu", "deferred"),
    (27, "Toolbar", "deferred"),
]

/// Returns the intrinsic standard events emitted by a standard node type.
///
/// This is generated from each node type's `emits` entry in the canonical registry.
/// Passive node properties such as `actions` and `action_key` do not add capability.
public func standardEventsEmitted(by nodeType: TypeRef) -> [TypeRef] {
    guard nodeType.isStandard else { return [] }
    switch nodeType.localID {
    case 1: return [TypeRef.EVENT_VIEWPORT_CHANGED]
    case 11: return [TypeRef.EVENT_ACTIVATE]
    case 12: return [TypeRef.EVENT_VALUE_CHANGED]
    case 13: return [TypeRef.EVENT_TEXT_EDIT]
    case 14: return [TypeRef.EVENT_TEXT_EDIT]
    case 17: return [TypeRef.EVENT_SELECTION_CHANGED]
    case 18: return [TypeRef.EVENT_SELECTION_CHANGED]
    case 19: return [TypeRef.EVENT_SELECTION_CHANGED, TypeRef.EVENT_EXPANSION_CHANGED]
    case 20: return [TypeRef.EVENT_SELECTION_CHANGED]
    case 21: return [TypeRef.EVENT_SELECTION_CHANGED]
    case 22: return [TypeRef.EVENT_VALUE_CHANGED]
    case 23: return [TypeRef.EVENT_VALUE_CHANGED]
    case 24: return [TypeRef.EVENT_SELECTION_CHANGED]
    case 25: return [TypeRef.EVENT_VALUE_CHANGED]
    default: return []
    }
}

public let standardPropertiesTable: [(id: UInt32, name: String)] = [
    (1, "label"),
    (2, "accessible_description"),
    (3, "role"),
    (4, "value_description"),
    (5, "actions"),
    (6, "visibility"),
    (7, "enabled"),
    (8, "read_only"),
    (9, "busy"),
    (10, "selected"),
    (11, "validation_state"),
    (12, "text"),
    (13, "value"),
    (14, "placeholder"),
    (15, "resource"),
    (16, "items"),
    (17, "model_ref"),
    (18, "horizontal_alignment"),
    (19, "vertical_alignment"),
    (20, "grow"),
    (21, "shrink"),
    (22, "minimum_size"),
    (23, "maximum_size"),
    (24, "preferred_size"),
    (25, "spacing_role"),
    (26, "padding_role"),
    (27, "presentation_hint"),
    (28, "action_key"),
    (29, "columns"),
    (30, "selection_mode"),
]

/// Runtime value kinds declared by the standard property registry.
public enum StandardPropertyValueType: String, Sendable {
    case any = "value"
    case bool
    case enumToken = "enum"
    case float64
    case list
    case resourceHash = "resource_hash"
    case size
    case string
    case unsignedInt = "uint64"
}

/// Returns the canonical runtime value kind for a standard property.
public func standardPropertyValueType(_ property: PropertyRef) -> StandardPropertyValueType? {
    guard property.isStandard else { return nil }
    switch property.localID {
    case 1: return .string
    case 2: return .string
    case 3: return .enumToken
    case 4: return .string
    case 5: return .list
    case 6: return .enumToken
    case 7: return .bool
    case 8: return .bool
    case 9: return .bool
    case 10: return .bool
    case 11: return .enumToken
    case 12: return .string
    case 13: return .any
    case 14: return .string
    case 15: return .resourceHash
    case 16: return .list
    case 17: return .unsignedInt
    case 18: return .enumToken
    case 19: return .enumToken
    case 20: return .float64
    case 21: return .float64
    case 22: return .size
    case 23: return .size
    case 24: return .size
    case 25: return .enumToken
    case 26: return .enumToken
    case 27: return .enumToken
    case 28: return .string
    case 29: return .list
    case 30: return .enumToken
    default: return nil
    }
}

public let standardEventsTable: [(id: UInt32, name: String)] = [
    (1, "ACTIVATE"),
    (2, "VALUE_CHANGED"),
    (3, "SELECTION_CHANGED"),
    (4, "EXPANSION_CHANGED"),
    (5, "TEXT_EDIT"),
    (6, "VIEWPORT_CHANGED"),
    (7, "POINTER_DOWN"),
    (8, "POINTER_UP"),
    (9, "POINTER_MOVE"),
    (10, "POINTER_CANCEL"),
    (11, "POINTER_SCROLL"),
]

public let standardOperationsTable: [(id: UInt32, name: String)] = [
    (1, "CREATE_NODE"),
    (2, "DELETE_NODE"),
    (3, "SET_PROPERTY"),
    (4, "CLEAR_PROPERTY"),
    (5, "COMMIT"),
    (6, "CREATE_MODEL"),
    (7, "MODEL_INSERT"),
    (8, "MODEL_DELETE"),
    (9, "MODEL_UPDATE"),
    (10, "MODEL_RESET_RANGE"),
    (11, "MOVE_NODE"),
    (12, "REORDER_CHILDREN"),
    (13, "BATCH_PROPERTY_SET"),
]

public let standardEnumsTable: [(id: UInt32, name: String)] = [
    (1, "TextRole"),
    (2, "ActionRole"),
    (3, "InputRole"),
    (4, "Importance"),
    (5, "TogglePresentationHint"),
    (6, "Visibility"),
    (7, "SpacingRole"),
    (8, "PaddingRole"),
    (9, "HorizontalAlignment"),
    (10, "VerticalAlignment"),
    (11, "SelectionMode"),
    (12, "ValidationState"),
]

// MARK: - Lookup Functions

public func lookupStandardNodeType(_ name: String) -> UInt32? {
    switch name {
    case "Surface": return 1
    case "Dialog": return 2
    case "Row": return 3
    case "Column": return 4
    case "Grid": return 5
    case "Spacer": return 6
    case "Separator": return 7
    case "Scroll": return 8
    case "Text": return 9
    case "RichText": return 10
    case "Button": return 11
    case "Toggle": return 12
    case "TextInput": return 13
    case "TextArea": return 14
    case "Progress": return 15
    case "Image": return 16
    case "List": return 17
    case "Table": return 18
    case "Tree": return 19
    case "Select": return 20
    case "ChoiceGroup": return 21
    case "Slider": return 22
    case "NumberInput": return 23
    case "Tabs": return 24
    case "Split": return 25
    case "Menu": return 26
    case "Toolbar": return 27
    default: return nil
    }
}

public func lookupStandardNodeTypeName(_ id: UInt32) -> String? {
    switch id {
    case 1: return "Surface"
    case 2: return "Dialog"
    case 3: return "Row"
    case 4: return "Column"
    case 5: return "Grid"
    case 6: return "Spacer"
    case 7: return "Separator"
    case 8: return "Scroll"
    case 9: return "Text"
    case 10: return "RichText"
    case 11: return "Button"
    case 12: return "Toggle"
    case 13: return "TextInput"
    case 14: return "TextArea"
    case 15: return "Progress"
    case 16: return "Image"
    case 17: return "List"
    case 18: return "Table"
    case 19: return "Tree"
    case 20: return "Select"
    case 21: return "ChoiceGroup"
    case 22: return "Slider"
    case 23: return "NumberInput"
    case 24: return "Tabs"
    case 25: return "Split"
    case 26: return "Menu"
    case 27: return "Toolbar"
    default: return nil
    }
}

public func standardNodeTypeName(_ id: UInt32) -> String? {
    lookupStandardNodeTypeName(id)
}

public func lookupStandardProperty(_ name: String) -> UInt32? {
    switch name {
    case "label": return 1
    case "accessible_description": return 2
    case "role": return 3
    case "value_description": return 4
    case "actions": return 5
    case "visibility": return 6
    case "enabled": return 7
    case "read_only": return 8
    case "busy": return 9
    case "selected": return 10
    case "validation_state": return 11
    case "text": return 12
    case "value": return 13
    case "placeholder": return 14
    case "resource": return 15
    case "items": return 16
    case "model_ref": return 17
    case "horizontal_alignment": return 18
    case "vertical_alignment": return 19
    case "grow": return 20
    case "shrink": return 21
    case "minimum_size": return 22
    case "maximum_size": return 23
    case "preferred_size": return 24
    case "spacing_role": return 25
    case "padding_role": return 26
    case "presentation_hint": return 27
    case "action_key": return 28
    case "columns": return 29
    case "selection_mode": return 30
    default: return nil
    }
}

public func lookupStandardPropertyName(_ id: UInt32) -> String? {
    switch id {
    case 1: return "label"
    case 2: return "accessible_description"
    case 3: return "role"
    case 4: return "value_description"
    case 5: return "actions"
    case 6: return "visibility"
    case 7: return "enabled"
    case 8: return "read_only"
    case 9: return "busy"
    case 10: return "selected"
    case 11: return "validation_state"
    case 12: return "text"
    case 13: return "value"
    case 14: return "placeholder"
    case 15: return "resource"
    case 16: return "items"
    case 17: return "model_ref"
    case 18: return "horizontal_alignment"
    case 19: return "vertical_alignment"
    case 20: return "grow"
    case 21: return "shrink"
    case 22: return "minimum_size"
    case 23: return "maximum_size"
    case 24: return "preferred_size"
    case 25: return "spacing_role"
    case 26: return "padding_role"
    case 27: return "presentation_hint"
    case 28: return "action_key"
    case 29: return "columns"
    case 30: return "selection_mode"
    default: return nil
    }
}

public func standardPropertyName(_ id: UInt32) -> String? {
    lookupStandardPropertyName(id)
}

public func lookupStandardEvent(_ name: String) -> UInt32? {
    switch name {
    case "ACTIVATE": return 1
    case "VALUE_CHANGED": return 2
    case "SELECTION_CHANGED": return 3
    case "EXPANSION_CHANGED": return 4
    case "TEXT_EDIT": return 5
    case "VIEWPORT_CHANGED": return 6
    case "POINTER_DOWN": return 7
    case "POINTER_UP": return 8
    case "POINTER_MOVE": return 9
    case "POINTER_CANCEL": return 10
    case "POINTER_SCROLL": return 11
    default: return nil
    }
}

public func lookupStandardEventName(_ id: UInt32) -> String? {
    switch id {
    case 1: return "ACTIVATE"
    case 2: return "VALUE_CHANGED"
    case 3: return "SELECTION_CHANGED"
    case 4: return "EXPANSION_CHANGED"
    case 5: return "TEXT_EDIT"
    case 6: return "VIEWPORT_CHANGED"
    case 7: return "POINTER_DOWN"
    case 8: return "POINTER_UP"
    case 9: return "POINTER_MOVE"
    case 10: return "POINTER_CANCEL"
    case 11: return "POINTER_SCROLL"
    default: return nil
    }
}

public func standardEventName(_ id: UInt32) -> String? {
    lookupStandardEventName(id)
}

public func lookupStandardOperation(_ name: String) -> UInt32? {
    switch name {
    case "CREATE_NODE": return 1
    case "DELETE_NODE": return 2
    case "SET_PROPERTY": return 3
    case "CLEAR_PROPERTY": return 4
    case "COMMIT": return 5
    case "CREATE_MODEL": return 6
    case "MODEL_INSERT": return 7
    case "MODEL_DELETE": return 8
    case "MODEL_UPDATE": return 9
    case "MODEL_RESET_RANGE": return 10
    case "MOVE_NODE": return 11
    case "REORDER_CHILDREN": return 12
    case "BATCH_PROPERTY_SET": return 13
    default: return nil
    }
}

public func lookupStandardOperationName(_ id: UInt32) -> String? {
    switch id {
    case 1: return "CREATE_NODE"
    case 2: return "DELETE_NODE"
    case 3: return "SET_PROPERTY"
    case 4: return "CLEAR_PROPERTY"
    case 5: return "COMMIT"
    case 6: return "CREATE_MODEL"
    case 7: return "MODEL_INSERT"
    case 8: return "MODEL_DELETE"
    case 9: return "MODEL_UPDATE"
    case 10: return "MODEL_RESET_RANGE"
    case 11: return "MOVE_NODE"
    case 12: return "REORDER_CHILDREN"
    case 13: return "BATCH_PROPERTY_SET"
    default: return nil
    }
}

public func standardOperationName(_ id: UInt32) -> String? {
    lookupStandardOperationName(id)
}

public func lookupStandardEnum(_ name: String) -> UInt32? {
    switch name {
    case "TextRole": return 1
    case "ActionRole": return 2
    case "InputRole": return 3
    case "Importance": return 4
    case "TogglePresentationHint": return 5
    case "Visibility": return 6
    case "SpacingRole": return 7
    case "PaddingRole": return 8
    case "HorizontalAlignment": return 9
    case "VerticalAlignment": return 10
    case "SelectionMode": return 11
    case "ValidationState": return 12
    default: return nil
    }
}

public func lookupStandardEnumName(_ id: UInt32) -> String? {
    switch id {
    case 1: return "TextRole"
    case 2: return "ActionRole"
    case 3: return "InputRole"
    case 4: return "Importance"
    case 5: return "TogglePresentationHint"
    case 6: return "Visibility"
    case 7: return "SpacingRole"
    case 8: return "PaddingRole"
    case 9: return "HorizontalAlignment"
    case 10: return "VerticalAlignment"
    case 11: return "SelectionMode"
    case 12: return "ValidationState"
    default: return nil
    }
}

public func standardEnumName(_ id: UInt32) -> String? {
    lookupStandardEnumName(id)
}

public func lookupStandardEnumValue(enumID: UInt32, valueName: String) -> UInt32? {
    switch enumID {
    case 1:
        switch valueName {
        case "title": return 1
        case "heading": return 2
        case "body": return 3
        case "caption": return 4
        case "code": return 5
        case "status": return 6
        case "warning": return 7
        case "error": return 8
        default: return nil
        }
    case 2:
        switch valueName {
        case "normal": return 1
        case "primary": return 2
        case "destructive": return 3
        case "quiet": return 4
        default: return nil
        }
    case 3:
        switch valueName {
        case "plain": return 1
        case "search": return 2
        case "secure": return 3
        case "command": return 4
        default: return nil
        }
    case 4:
        switch valueName {
        case "normal": return 1
        case "emphasized": return 2
        case "de_emphasized": return 3
        default: return nil
        }
    case 5:
        switch valueName {
        case "automatic": return 1
        case "checkbox": return 2
        case "switch": return 3
        default: return nil
        }
    case 6:
        switch valueName {
        case "visible": return 1
        case "hidden": return 2
        case "collapsed": return 3
        default: return nil
        }
    case 7:
        switch valueName {
        case "none": return 1
        case "tight": return 2
        case "normal": return 3
        case "relaxed": return 4
        default: return nil
        }
    case 8:
        switch valueName {
        case "none": return 1
        case "tight": return 2
        case "normal": return 3
        case "relaxed": return 4
        default: return nil
        }
    case 9:
        switch valueName {
        case "leading": return 1
        case "center": return 2
        case "trailing": return 3
        case "fill": return 4
        default: return nil
        }
    case 10:
        switch valueName {
        case "top": return 1
        case "center": return 2
        case "bottom": return 3
        case "fill": return 4
        default: return nil
        }
    case 11:
        switch valueName {
        case "none": return 1
        case "single": return 2
        case "multiple": return 3
        default: return nil
        }
    case 12:
        switch valueName {
        case "valid": return 1
        case "warning": return 2
        case "error": return 3
        default: return nil
        }
    default: return nil
    }
}

public func lookupStandardEnumValueName(enumID: UInt32, valueID: UInt32) -> String? {
    switch (enumID, valueID) {
    case (1, 1): return "title"
    case (1, 2): return "heading"
    case (1, 3): return "body"
    case (1, 4): return "caption"
    case (1, 5): return "code"
    case (1, 6): return "status"
    case (1, 7): return "warning"
    case (1, 8): return "error"
    case (2, 1): return "normal"
    case (2, 2): return "primary"
    case (2, 3): return "destructive"
    case (2, 4): return "quiet"
    case (3, 1): return "plain"
    case (3, 2): return "search"
    case (3, 3): return "secure"
    case (3, 4): return "command"
    case (4, 1): return "normal"
    case (4, 2): return "emphasized"
    case (4, 3): return "de_emphasized"
    case (5, 1): return "automatic"
    case (5, 2): return "checkbox"
    case (5, 3): return "switch"
    case (6, 1): return "visible"
    case (6, 2): return "hidden"
    case (6, 3): return "collapsed"
    case (7, 1): return "none"
    case (7, 2): return "tight"
    case (7, 3): return "normal"
    case (7, 4): return "relaxed"
    case (8, 1): return "none"
    case (8, 2): return "tight"
    case (8, 3): return "normal"
    case (8, 4): return "relaxed"
    case (9, 1): return "leading"
    case (9, 2): return "center"
    case (9, 3): return "trailing"
    case (9, 4): return "fill"
    case (10, 1): return "top"
    case (10, 2): return "center"
    case (10, 3): return "bottom"
    case (10, 4): return "fill"
    case (11, 1): return "none"
    case (11, 2): return "single"
    case (11, 3): return "multiple"
    case (12, 1): return "valid"
    case (12, 2): return "warning"
    case (12, 3): return "error"
    default: return nil
    }
}

public func standardEnumValueName(enumID: UInt32, valueID: UInt32) -> String? {
    lookupStandardEnumValueName(enumID: enumID, valueID: valueID)
}

public func resolveStandardEnumValue(enumName: String, valueName: String) -> EnumToken? {
    switch enumName {
    case "TextRole", "EnumTextRole":
        switch valueName {
        case "title": return EnumToken(enumID: 1, valueID: 1)
        case "heading": return EnumToken(enumID: 1, valueID: 2)
        case "body": return EnumToken(enumID: 1, valueID: 3)
        case "caption": return EnumToken(enumID: 1, valueID: 4)
        case "code": return EnumToken(enumID: 1, valueID: 5)
        case "status": return EnumToken(enumID: 1, valueID: 6)
        case "warning": return EnumToken(enumID: 1, valueID: 7)
        case "error": return EnumToken(enumID: 1, valueID: 8)
        default: return nil
        }
    case "ActionRole", "EnumActionRole":
        switch valueName {
        case "normal": return EnumToken(enumID: 2, valueID: 1)
        case "primary": return EnumToken(enumID: 2, valueID: 2)
        case "destructive": return EnumToken(enumID: 2, valueID: 3)
        case "quiet": return EnumToken(enumID: 2, valueID: 4)
        default: return nil
        }
    case "InputRole", "EnumInputRole":
        switch valueName {
        case "plain": return EnumToken(enumID: 3, valueID: 1)
        case "search": return EnumToken(enumID: 3, valueID: 2)
        case "secure": return EnumToken(enumID: 3, valueID: 3)
        case "command": return EnumToken(enumID: 3, valueID: 4)
        default: return nil
        }
    case "Importance", "EnumImportance":
        switch valueName {
        case "normal": return EnumToken(enumID: 4, valueID: 1)
        case "emphasized": return EnumToken(enumID: 4, valueID: 2)
        case "de_emphasized": return EnumToken(enumID: 4, valueID: 3)
        default: return nil
        }
    case "TogglePresentationHint", "EnumTogglePresentationHint":
        switch valueName {
        case "automatic": return EnumToken(enumID: 5, valueID: 1)
        case "checkbox": return EnumToken(enumID: 5, valueID: 2)
        case "switch": return EnumToken(enumID: 5, valueID: 3)
        default: return nil
        }
    case "Visibility", "EnumVisibility":
        switch valueName {
        case "visible": return EnumToken(enumID: 6, valueID: 1)
        case "hidden": return EnumToken(enumID: 6, valueID: 2)
        case "collapsed": return EnumToken(enumID: 6, valueID: 3)
        default: return nil
        }
    case "SpacingRole", "EnumSpacingRole":
        switch valueName {
        case "none": return EnumToken(enumID: 7, valueID: 1)
        case "tight": return EnumToken(enumID: 7, valueID: 2)
        case "normal": return EnumToken(enumID: 7, valueID: 3)
        case "relaxed": return EnumToken(enumID: 7, valueID: 4)
        default: return nil
        }
    case "PaddingRole", "EnumPaddingRole":
        switch valueName {
        case "none": return EnumToken(enumID: 8, valueID: 1)
        case "tight": return EnumToken(enumID: 8, valueID: 2)
        case "normal": return EnumToken(enumID: 8, valueID: 3)
        case "relaxed": return EnumToken(enumID: 8, valueID: 4)
        default: return nil
        }
    case "HorizontalAlignment", "EnumHorizontalAlignment":
        switch valueName {
        case "leading": return EnumToken(enumID: 9, valueID: 1)
        case "center": return EnumToken(enumID: 9, valueID: 2)
        case "trailing": return EnumToken(enumID: 9, valueID: 3)
        case "fill": return EnumToken(enumID: 9, valueID: 4)
        default: return nil
        }
    case "VerticalAlignment", "EnumVerticalAlignment":
        switch valueName {
        case "top": return EnumToken(enumID: 10, valueID: 1)
        case "center": return EnumToken(enumID: 10, valueID: 2)
        case "bottom": return EnumToken(enumID: 10, valueID: 3)
        case "fill": return EnumToken(enumID: 10, valueID: 4)
        default: return nil
        }
    case "SelectionMode", "EnumSelectionMode":
        switch valueName {
        case "none": return EnumToken(enumID: 11, valueID: 1)
        case "single": return EnumToken(enumID: 11, valueID: 2)
        case "multiple": return EnumToken(enumID: 11, valueID: 3)
        default: return nil
        }
    case "ValidationState", "EnumValidationState":
        switch valueName {
        case "valid": return EnumToken(enumID: 12, valueID: 1)
        case "warning": return EnumToken(enumID: 12, valueID: 2)
        case "error": return EnumToken(enumID: 12, valueID: 3)
        default: return nil
        }
    default: return nil
    }
}

// MARK: - Standard TypeRef Constants

extension TypeRef {
    public static let surface = TypeRef.standard(1)
    public static let SURFACE = TypeRef.standard(1)
    public static let dialog = TypeRef.standard(2)
    public static let DIALOG = TypeRef.standard(2)
    public static let row = TypeRef.standard(3)
    public static let ROW = TypeRef.standard(3)
    public static let column = TypeRef.standard(4)
    public static let COLUMN = TypeRef.standard(4)
    public static let grid = TypeRef.standard(5)
    public static let GRID = TypeRef.standard(5)
    public static let spacer = TypeRef.standard(6)
    public static let SPACER = TypeRef.standard(6)
    public static let separator = TypeRef.standard(7)
    public static let SEPARATOR = TypeRef.standard(7)
    public static let scroll = TypeRef.standard(8)
    public static let SCROLL = TypeRef.standard(8)
    public static let text = TypeRef.standard(9)
    public static let TEXT = TypeRef.standard(9)
    public static let richText = TypeRef.standard(10)
    public static let RICH_TEXT = TypeRef.standard(10)
    public static let RICHTEXT = TypeRef.standard(10)
    public static let button = TypeRef.standard(11)
    public static let BUTTON = TypeRef.standard(11)
    public static let toggle = TypeRef.standard(12)
    public static let TOGGLE = TypeRef.standard(12)
    public static let textInput = TypeRef.standard(13)
    public static let TEXT_INPUT = TypeRef.standard(13)
    public static let textArea = TypeRef.standard(14)
    public static let TEXT_AREA = TypeRef.standard(14)
    public static let progress = TypeRef.standard(15)
    public static let PROGRESS = TypeRef.standard(15)
    public static let image = TypeRef.standard(16)
    public static let IMAGE = TypeRef.standard(16)
    public static let list = TypeRef.standard(17)
    public static let LIST = TypeRef.standard(17)
    public static let table = TypeRef.standard(18)
    public static let TABLE = TypeRef.standard(18)
    public static let tree = TypeRef.standard(19)
    public static let TREE = TypeRef.standard(19)
    public static let select = TypeRef.standard(20)
    public static let SELECT = TypeRef.standard(20)
    public static let choiceGroup = TypeRef.standard(21)
    public static let CHOICE_GROUP = TypeRef.standard(21)
    public static let slider = TypeRef.standard(22)
    public static let SLIDER = TypeRef.standard(22)
    public static let numberInput = TypeRef.standard(23)
    public static let NUMBER_INPUT = TypeRef.standard(23)
    public static let tabs = TypeRef.standard(24)
    public static let TABS = TypeRef.standard(24)
    public static let split = TypeRef.standard(25)
    public static let SPLIT = TypeRef.standard(25)
    public static let menu = TypeRef.standard(26)
    public static let MENU = TypeRef.standard(26)
    public static let toolbar = TypeRef.standard(27)
    public static let TOOLBAR = TypeRef.standard(27)
    public static let eventActivate = TypeRef.standard(1)
    public static let EVENT_ACTIVATE = TypeRef.standard(1)
    public static let eventValueChanged = TypeRef.standard(2)
    public static let EVENT_VALUE_CHANGED = TypeRef.standard(2)
    public static let eventSelectionChanged = TypeRef.standard(3)
    public static let EVENT_SELECTION_CHANGED = TypeRef.standard(3)
    public static let eventExpansionChanged = TypeRef.standard(4)
    public static let EVENT_EXPANSION_CHANGED = TypeRef.standard(4)
    public static let eventTextEdit = TypeRef.standard(5)
    public static let EVENT_TEXT_EDIT = TypeRef.standard(5)
    public static let eventViewportChanged = TypeRef.standard(6)
    public static let EVENT_VIEWPORT_CHANGED = TypeRef.standard(6)
    public static let eventPointerDown = TypeRef.standard(7)
    public static let EVENT_POINTER_DOWN = TypeRef.standard(7)
    public static let eventPointerUp = TypeRef.standard(8)
    public static let EVENT_POINTER_UP = TypeRef.standard(8)
    public static let eventPointerMove = TypeRef.standard(9)
    public static let EVENT_POINTER_MOVE = TypeRef.standard(9)
    public static let eventPointerCancel = TypeRef.standard(10)
    public static let EVENT_POINTER_CANCEL = TypeRef.standard(10)
    public static let eventPointerScroll = TypeRef.standard(11)
    public static let EVENT_POINTER_SCROLL = TypeRef.standard(11)
}

// MARK: - Standard PropertyRef Constants

extension PropertyRef {
    public static let label = PropertyRef.standard(1)
    public static let LABEL = PropertyRef.standard(1)
    public static let accessibleDescription = PropertyRef.standard(2)
    public static let ACCESSIBLE_DESCRIPTION = PropertyRef.standard(2)
    public static let role = PropertyRef.standard(3)
    public static let ROLE = PropertyRef.standard(3)
    public static let valueDescription = PropertyRef.standard(4)
    public static let VALUE_DESCRIPTION = PropertyRef.standard(4)
    public static let actions = PropertyRef.standard(5)
    public static let ACTIONS = PropertyRef.standard(5)
    public static let visibility = PropertyRef.standard(6)
    public static let VISIBILITY = PropertyRef.standard(6)
    public static let enabled = PropertyRef.standard(7)
    public static let ENABLED = PropertyRef.standard(7)
    public static let readOnly = PropertyRef.standard(8)
    public static let READ_ONLY = PropertyRef.standard(8)
    public static let busy = PropertyRef.standard(9)
    public static let BUSY = PropertyRef.standard(9)
    public static let selected = PropertyRef.standard(10)
    public static let SELECTED = PropertyRef.standard(10)
    public static let validationState = PropertyRef.standard(11)
    public static let VALIDATION_STATE = PropertyRef.standard(11)
    public static let text = PropertyRef.standard(12)
    public static let TEXT = PropertyRef.standard(12)
    public static let value = PropertyRef.standard(13)
    public static let VALUE = PropertyRef.standard(13)
    public static let placeholder = PropertyRef.standard(14)
    public static let PLACEHOLDER = PropertyRef.standard(14)
    public static let resource = PropertyRef.standard(15)
    public static let RESOURCE = PropertyRef.standard(15)
    public static let items = PropertyRef.standard(16)
    public static let ITEMS = PropertyRef.standard(16)
    public static let modelRef = PropertyRef.standard(17)
    public static let MODEL_REF = PropertyRef.standard(17)
    public static let horizontalAlignment = PropertyRef.standard(18)
    public static let HORIZONTAL_ALIGNMENT = PropertyRef.standard(18)
    public static let verticalAlignment = PropertyRef.standard(19)
    public static let VERTICAL_ALIGNMENT = PropertyRef.standard(19)
    public static let grow = PropertyRef.standard(20)
    public static let GROW = PropertyRef.standard(20)
    public static let shrink = PropertyRef.standard(21)
    public static let SHRINK = PropertyRef.standard(21)
    public static let minimumSize = PropertyRef.standard(22)
    public static let MINIMUM_SIZE = PropertyRef.standard(22)
    public static let maximumSize = PropertyRef.standard(23)
    public static let MAXIMUM_SIZE = PropertyRef.standard(23)
    public static let preferredSize = PropertyRef.standard(24)
    public static let PREFERRED_SIZE = PropertyRef.standard(24)
    public static let spacingRole = PropertyRef.standard(25)
    public static let SPACING_ROLE = PropertyRef.standard(25)
    public static let paddingRole = PropertyRef.standard(26)
    public static let PADDING_ROLE = PropertyRef.standard(26)
    public static let presentationHint = PropertyRef.standard(27)
    public static let PRESENTATION_HINT = PropertyRef.standard(27)
    public static let actionKey = PropertyRef.standard(28)
    public static let ACTION_KEY = PropertyRef.standard(28)
    public static let columns = PropertyRef.standard(29)
    public static let COLUMNS = PropertyRef.standard(29)
    public static let selectionMode = PropertyRef.standard(30)
    public static let SELECTION_MODE = PropertyRef.standard(30)
}

// MARK: - Standard EnumToken Constants

extension EnumToken {
    public static let textRoleTitle = EnumToken(enumID: 1, valueID: 1)
    public static let TEXT_ROLE_TITLE = EnumToken(enumID: 1, valueID: 1)
    public static let textRoleHeading = EnumToken(enumID: 1, valueID: 2)
    public static let TEXT_ROLE_HEADING = EnumToken(enumID: 1, valueID: 2)
    public static let textRoleBody = EnumToken(enumID: 1, valueID: 3)
    public static let TEXT_ROLE_BODY = EnumToken(enumID: 1, valueID: 3)
    public static let textRoleCaption = EnumToken(enumID: 1, valueID: 4)
    public static let TEXT_ROLE_CAPTION = EnumToken(enumID: 1, valueID: 4)
    public static let textRoleCode = EnumToken(enumID: 1, valueID: 5)
    public static let TEXT_ROLE_CODE = EnumToken(enumID: 1, valueID: 5)
    public static let textRoleStatus = EnumToken(enumID: 1, valueID: 6)
    public static let TEXT_ROLE_STATUS = EnumToken(enumID: 1, valueID: 6)
    public static let textRoleWarning = EnumToken(enumID: 1, valueID: 7)
    public static let TEXT_ROLE_WARNING = EnumToken(enumID: 1, valueID: 7)
    public static let textRoleError = EnumToken(enumID: 1, valueID: 8)
    public static let TEXT_ROLE_ERROR = EnumToken(enumID: 1, valueID: 8)
    public static let actionRoleNormal = EnumToken(enumID: 2, valueID: 1)
    public static let ACTION_ROLE_NORMAL = EnumToken(enumID: 2, valueID: 1)
    public static let actionRolePrimary = EnumToken(enumID: 2, valueID: 2)
    public static let ACTION_ROLE_PRIMARY = EnumToken(enumID: 2, valueID: 2)
    public static let actionRoleDestructive = EnumToken(enumID: 2, valueID: 3)
    public static let ACTION_ROLE_DESTRUCTIVE = EnumToken(enumID: 2, valueID: 3)
    public static let actionRoleQuiet = EnumToken(enumID: 2, valueID: 4)
    public static let ACTION_ROLE_QUIET = EnumToken(enumID: 2, valueID: 4)
    public static let inputRolePlain = EnumToken(enumID: 3, valueID: 1)
    public static let INPUT_ROLE_PLAIN = EnumToken(enumID: 3, valueID: 1)
    public static let inputRoleSearch = EnumToken(enumID: 3, valueID: 2)
    public static let INPUT_ROLE_SEARCH = EnumToken(enumID: 3, valueID: 2)
    public static let inputRoleSecure = EnumToken(enumID: 3, valueID: 3)
    public static let INPUT_ROLE_SECURE = EnumToken(enumID: 3, valueID: 3)
    public static let inputRoleCommand = EnumToken(enumID: 3, valueID: 4)
    public static let INPUT_ROLE_COMMAND = EnumToken(enumID: 3, valueID: 4)
    public static let importanceNormal = EnumToken(enumID: 4, valueID: 1)
    public static let IMPORTANCE_NORMAL = EnumToken(enumID: 4, valueID: 1)
    public static let importanceEmphasized = EnumToken(enumID: 4, valueID: 2)
    public static let IMPORTANCE_EMPHASIZED = EnumToken(enumID: 4, valueID: 2)
    public static let importanceDeEmphasized = EnumToken(enumID: 4, valueID: 3)
    public static let IMPORTANCE_DE_EMPHASIZED = EnumToken(enumID: 4, valueID: 3)
    public static let togglePresentationHintAutomatic = EnumToken(enumID: 5, valueID: 1)
    public static let TOGGLE_PRESENTATION_HINT_AUTOMATIC = EnumToken(enumID: 5, valueID: 1)
    public static let togglePresentationHintCheckbox = EnumToken(enumID: 5, valueID: 2)
    public static let TOGGLE_PRESENTATION_HINT_CHECKBOX = EnumToken(enumID: 5, valueID: 2)
    public static let togglePresentationHintSwitch = EnumToken(enumID: 5, valueID: 3)
    public static let TOGGLE_PRESENTATION_HINT_SWITCH = EnumToken(enumID: 5, valueID: 3)
    public static let visibilityVisible = EnumToken(enumID: 6, valueID: 1)
    public static let VISIBILITY_VISIBLE = EnumToken(enumID: 6, valueID: 1)
    public static let visibilityHidden = EnumToken(enumID: 6, valueID: 2)
    public static let VISIBILITY_HIDDEN = EnumToken(enumID: 6, valueID: 2)
    public static let visibilityCollapsed = EnumToken(enumID: 6, valueID: 3)
    public static let VISIBILITY_COLLAPSED = EnumToken(enumID: 6, valueID: 3)
    public static let spacingRoleNone = EnumToken(enumID: 7, valueID: 1)
    public static let SPACING_ROLE_NONE = EnumToken(enumID: 7, valueID: 1)
    public static let spacingRoleTight = EnumToken(enumID: 7, valueID: 2)
    public static let SPACING_ROLE_TIGHT = EnumToken(enumID: 7, valueID: 2)
    public static let spacingRoleNormal = EnumToken(enumID: 7, valueID: 3)
    public static let SPACING_ROLE_NORMAL = EnumToken(enumID: 7, valueID: 3)
    public static let spacingRoleRelaxed = EnumToken(enumID: 7, valueID: 4)
    public static let SPACING_ROLE_RELAXED = EnumToken(enumID: 7, valueID: 4)
    public static let paddingRoleNone = EnumToken(enumID: 8, valueID: 1)
    public static let PADDING_ROLE_NONE = EnumToken(enumID: 8, valueID: 1)
    public static let paddingRoleTight = EnumToken(enumID: 8, valueID: 2)
    public static let PADDING_ROLE_TIGHT = EnumToken(enumID: 8, valueID: 2)
    public static let paddingRoleNormal = EnumToken(enumID: 8, valueID: 3)
    public static let PADDING_ROLE_NORMAL = EnumToken(enumID: 8, valueID: 3)
    public static let paddingRoleRelaxed = EnumToken(enumID: 8, valueID: 4)
    public static let PADDING_ROLE_RELAXED = EnumToken(enumID: 8, valueID: 4)
    public static let horizontalAlignmentLeading = EnumToken(enumID: 9, valueID: 1)
    public static let HORIZONTAL_ALIGNMENT_LEADING = EnumToken(enumID: 9, valueID: 1)
    public static let horizontalAlignmentCenter = EnumToken(enumID: 9, valueID: 2)
    public static let HORIZONTAL_ALIGNMENT_CENTER = EnumToken(enumID: 9, valueID: 2)
    public static let horizontalAlignmentTrailing = EnumToken(enumID: 9, valueID: 3)
    public static let HORIZONTAL_ALIGNMENT_TRAILING = EnumToken(enumID: 9, valueID: 3)
    public static let horizontalAlignmentFill = EnumToken(enumID: 9, valueID: 4)
    public static let HORIZONTAL_ALIGNMENT_FILL = EnumToken(enumID: 9, valueID: 4)
    public static let verticalAlignmentTop = EnumToken(enumID: 10, valueID: 1)
    public static let VERTICAL_ALIGNMENT_TOP = EnumToken(enumID: 10, valueID: 1)
    public static let verticalAlignmentCenter = EnumToken(enumID: 10, valueID: 2)
    public static let VERTICAL_ALIGNMENT_CENTER = EnumToken(enumID: 10, valueID: 2)
    public static let verticalAlignmentBottom = EnumToken(enumID: 10, valueID: 3)
    public static let VERTICAL_ALIGNMENT_BOTTOM = EnumToken(enumID: 10, valueID: 3)
    public static let verticalAlignmentFill = EnumToken(enumID: 10, valueID: 4)
    public static let VERTICAL_ALIGNMENT_FILL = EnumToken(enumID: 10, valueID: 4)
    public static let selectionModeNone = EnumToken(enumID: 11, valueID: 1)
    public static let SELECTION_MODE_NONE = EnumToken(enumID: 11, valueID: 1)
    public static let selectionModeSingle = EnumToken(enumID: 11, valueID: 2)
    public static let SELECTION_MODE_SINGLE = EnumToken(enumID: 11, valueID: 2)
    public static let selectionModeMultiple = EnumToken(enumID: 11, valueID: 3)
    public static let SELECTION_MODE_MULTIPLE = EnumToken(enumID: 11, valueID: 3)
    public static let validationStateValid = EnumToken(enumID: 12, valueID: 1)
    public static let VALIDATION_STATE_VALID = EnumToken(enumID: 12, valueID: 1)
    public static let validationStateWarning = EnumToken(enumID: 12, valueID: 2)
    public static let VALIDATION_STATE_WARNING = EnumToken(enumID: 12, valueID: 2)
    public static let validationStateError = EnumToken(enumID: 12, valueID: 3)
    public static let VALIDATION_STATE_ERROR = EnumToken(enumID: 12, valueID: 3)
}

// MARK: - Typed Standard Enums

public enum StandardTextRole: UInt32, CaseIterable, Sendable {
    case title = 1
    case heading = 2
    case body = 3
    case caption = 4
    case code = 5
    case status = 6
    case warning = 7
    case error = 8

    public static let standardEnumID: UInt32 = 1

    public var enumToken: EnumToken {
        EnumToken(enumID: 1, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 1 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardActionRole: UInt32, CaseIterable, Sendable {
    case normal = 1
    case primary = 2
    case destructive = 3
    case quiet = 4

    public static let standardEnumID: UInt32 = 2

    public var enumToken: EnumToken {
        EnumToken(enumID: 2, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 2 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardInputRole: UInt32, CaseIterable, Sendable {
    case plain = 1
    case search = 2
    case secure = 3
    case command = 4

    public static let standardEnumID: UInt32 = 3

    public var enumToken: EnumToken {
        EnumToken(enumID: 3, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 3 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardImportance: UInt32, CaseIterable, Sendable {
    case normal = 1
    case emphasized = 2
    case deEmphasized = 3

    public static let standardEnumID: UInt32 = 4

    public var enumToken: EnumToken {
        EnumToken(enumID: 4, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 4 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardTogglePresentationHint: UInt32, CaseIterable, Sendable {
    case automatic = 1
    case checkbox = 2
    case `switch` = 3

    public static let standardEnumID: UInt32 = 5

    public var enumToken: EnumToken {
        EnumToken(enumID: 5, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 5 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardVisibility: UInt32, CaseIterable, Sendable {
    case visible = 1
    case hidden = 2
    case collapsed = 3

    public static let standardEnumID: UInt32 = 6

    public var enumToken: EnumToken {
        EnumToken(enumID: 6, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 6 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardSpacingRole: UInt32, CaseIterable, Sendable {
    case none = 1
    case tight = 2
    case normal = 3
    case relaxed = 4

    public static let standardEnumID: UInt32 = 7

    public var enumToken: EnumToken {
        EnumToken(enumID: 7, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 7 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardPaddingRole: UInt32, CaseIterable, Sendable {
    case none = 1
    case tight = 2
    case normal = 3
    case relaxed = 4

    public static let standardEnumID: UInt32 = 8

    public var enumToken: EnumToken {
        EnumToken(enumID: 8, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 8 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardHorizontalAlignment: UInt32, CaseIterable, Sendable {
    case leading = 1
    case center = 2
    case trailing = 3
    case fill = 4

    public static let standardEnumID: UInt32 = 9

    public var enumToken: EnumToken {
        EnumToken(enumID: 9, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 9 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardVerticalAlignment: UInt32, CaseIterable, Sendable {
    case top = 1
    case center = 2
    case bottom = 3
    case fill = 4

    public static let standardEnumID: UInt32 = 10

    public var enumToken: EnumToken {
        EnumToken(enumID: 10, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 10 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardSelectionMode: UInt32, CaseIterable, Sendable {
    case none = 1
    case single = 2
    case multiple = 3

    public static let standardEnumID: UInt32 = 11

    public var enumToken: EnumToken {
        EnumToken(enumID: 11, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 11 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

public enum StandardValidationState: UInt32, CaseIterable, Sendable {
    case valid = 1
    case warning = 2
    case error = 3

    public static let standardEnumID: UInt32 = 12

    public var enumToken: EnumToken {
        EnumToken(enumID: 12, valueID: self.rawValue)
    }

    public init?(enumToken: EnumToken) {
        guard enumToken.enumID == 12 else { return nil }
        self.init(rawValue: enumToken.valueID)
    }
}

